package com.martonegyed.presentation.components.insights

private val countryAlpha2ByNormalizedName: Map<String, String> = mapOf(
    "afghanistan" to "AF",
    "albania" to "AL",
    "algeria" to "DZ",
    "angola" to "AO",
    "antarctica" to "AQ",
    "argentina" to "AR",
    "armenia" to "AM",
    "australia" to "AU",
    "austria" to "AT",
    "azerbaijan" to "AZ",
    "bahamas" to "BS",
    "bangladesh" to "BD",
    "belarus" to "BY",
    "belgium" to "BE",
    "belize" to "BZ",
    "benin" to "BJ",
    "bhutan" to "BT",
    "bolivia" to "BO",
    "bosnia and herz." to "BA",
    "bosnia and herzegovina" to "BA",
    "botswana" to "BW",
    "brazil" to "BR",
    "brunei" to "BN",
    "bulgaria" to "BG",
    "burkina faso" to "BF",
    "burundi" to "BI",
    "cambodia" to "KH",
    "cameroon" to "CM",
    "canada" to "CA",
    "central african rep." to "CF",
    "central african republic" to "CF",
    "chad" to "TD",
    "chile" to "CL",
    "china" to "CN",
    "colombia" to "CO",
    "congo" to "CG",
    "costa rica" to "CR",
    "croatia" to "HR",
    "cuba" to "CU",
    "cyprus" to "CY",
    "czech republic" to "CZ",
    "czechia" to "CZ",
    "côte d'ivoire" to "CI",
    "dem. rep. congo" to "CD",
    "dem. rep. korea" to "KP",
    "democratic republic of the congo" to "CD",
    "denmark" to "DK",
    "djibouti" to "DJ",
    "dominican rep." to "DO",
    "dominican republic" to "DO",
    "ecuador" to "EC",
    "egypt" to "EG",
    "el salvador" to "SV",
    "eq. guinea" to "GQ",
    "equatorial guinea" to "GQ",
    "eritrea" to "ER",
    "estonia" to "EE",
    "eswatini" to "SZ",
    "eswatini" to "SZ",
    "ethiopia" to "ET",
    "falkland is." to "FK",
    "falkland islands" to "FK",
    "fiji" to "FJ",
    "finland" to "FI",
    "france" to "FR",
    "french guiana" to "GF",
    "french polynesia" to "PF",
    "french southern and antarctic lands" to "TF",
    "gabon" to "GA",
    "gambia" to "GM",
    "georgia" to "GE",
    "germany" to "DE",
    "ghana" to "GH",
    "great britain" to "GB",
    "greece" to "GR",
    "greenland" to "GL",
    "guatemala" to "GT",
    "guinea" to "GN",
    "guinea-bissau" to "GW",
    "guyana" to "GY",
    "haiti" to "HT",
    "honduras" to "HN",
    "hungary" to "HU",
    "iceland" to "IS",
    "india" to "IN",
    "indonesia" to "ID",
    "iran" to "IR",
    "iran (islamic republic of)" to "IR",
    "iraq" to "IQ",
    "ireland" to "IE",
    "israel" to "IL",
    "italy" to "IT",
    "ivory coast" to "CI",
    "jamaica" to "JM",
    "japan" to "JP",
    "jordan" to "JO",
    "kazakhstan" to "KZ",
    "kenya" to "KE",
    "korea, republic of" to "KR",
    "kosovo" to "XK",
    "kuwait" to "KW",
    "kyrgyzstan" to "KG",
    "lao people's democratic republic" to "LA",
    "laos" to "LA",
    "latvia" to "LV",
    "lebanon" to "LB",
    "lesotho" to "LS",
    "liberia" to "LR",
    "libya" to "LY",
    "lithuania" to "LT",
    "luxembourg" to "LU",
    "macedonia" to "MK",
    "madagascar" to "MG",
    "malawi" to "MW",
    "malaysia" to "MY",
    "mali" to "ML",
    "mauritania" to "MR",
    "mexico" to "MX",
    "moldova" to "MD",
    "mongolia" to "MN",
    "montenegro" to "ME",
    "morocco" to "MA",
    "mozambique" to "MZ",
    "myanmar" to "MM",
    "namibia" to "NA",
    "nepal" to "NP",
    "netherlands" to "NL",
    "new caledonia" to "NC",
    "new zealand" to "NZ",
    "nicaragua" to "NI",
    "niger" to "NE",
    "nigeria" to "NG",
    "north korea" to "KP",
    "north macedonia" to "MK",
    "norway" to "NO",
    "oman" to "OM",
    "pakistan" to "PK",
    "palestine" to "PS",
    "panama" to "PA",
    "papua new guinea" to "PG",
    "paraguay" to "PY",
    "peru" to "PE",
    "philippines" to "PH",
    "poland" to "PL",
    "portugal" to "PT",
    "puerto rico" to "PR",
    "qatar" to "QA",
    "republic of moldova" to "MD",
    "republic of the congo" to "CG",
    "romania" to "RO",
    "russia" to "RU",
    "russian federation" to "RU",
    "rwanda" to "RW",
    "saudi arabia" to "SA",
    "senegal" to "SN",
    "serbia" to "RS",
    "sierra leone" to "SL",
    "slovakia" to "SK",
    "slovenia" to "SI",
    "solomon is." to "SB",
    "solomon islands" to "SB",
    "somalia" to "SO",
    "somaliland" to "XS",
    "south africa" to "ZA",
    "south korea" to "KR",
    "south sudan" to "SS",
    "spain" to "ES",
    "sri lanka" to "LK",
    "sudan" to "SD",
    "suriname" to "SR",
    "svalbard and jan mayen" to "SJ",
    "sweden" to "SE",
    "switzerland" to "CH",
    "syria" to "SY",
    "syrian arab republic" to "SY",
    "taiwan" to "TW",
    "taiwan (province of china)" to "TW",
    "tajikistan" to "TJ",
    "tanzania" to "TZ",
    "thailand" to "TH",
    "timor-leste" to "TL",
    "togo" to "TG",
    "trinidad and tobago" to "TT",
    "tunisia" to "TN",
    "turkey" to "TR",
    "turkmenistan" to "TM",
    "uganda" to "UG",
    "uk" to "GB",
    "ukraine" to "UA",
    "united arab emirates" to "AE",
    "united kingdom" to "GB",
    "united republic of tanzania" to "TZ",
    "united states" to "US",
    "united states of america" to "US",
    "uruguay" to "UY",
    "us" to "US",
    "usa" to "US",
    "uzbekistan" to "UZ",
    "vanuatu" to "VU",
    "venezuela" to "VE",
    "venezuela (bolivarian republic of)" to "VE",
    "viet nam" to "VN",
    "vietnam" to "VN",
    "w. sahara" to "EH",
    "western sahara" to "EH",
    "yemen" to "YE",
    "zambia" to "ZM",
    "zimbabwe" to "ZW",
)

fun countryAlpha2Code(countryName: String): String? {
    val normalized = normalizeCountryName(countryName)
    return countryAlpha2ByNormalizedName[normalized]
}

fun countryFlagEmoji(countryName: String): String {
    val alpha2 = countryAlpha2Code(countryName) ?: return ""
    if (alpha2.length != 2) return ""

    val code = alpha2.uppercase()
    val first = code[0].code - 'A'.code + 0x1F1E6
    val second = code[1].code - 'A'.code + 0x1F1E6

    fun codePointToString(cp: Int): String {
        return if (cp <= 0xFFFF) {
            charArrayOf(cp.toChar()).concatToString()
        } else {
            val u = cp - 0x10000
            val high = ((u shr 10) + 0xD800).toChar()
            val low = ((u and 0x3FF) + 0xDC00).toChar()
            charArrayOf(high, low).concatToString()
        }
    }

    return codePointToString(first) + codePointToString(second)
}